Controllers/AdminFilmsController.cs
using ECO._2015.Bussiness;
using ECO._2015.Models.App;
using ECO._2015.Models.ViewsModels;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;


namespace ECO._2015.Models
{
    public class AdminFilmsController : AdminFilmsBusssines
    {
        /*------------------------------------------------*/
        /*------------------------------------------------*/
        /*------------------------------------------------*/
        #region Index
        // GET: AdminFilms
        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var _filter = new AdminFilmsFilterViewModel()
            {
                Activo = true ,
                Preseleccion = false,
                Sel_Oficial = false,
                Ganador = false,
                Etapa = EtapaRegistroFin ,
                Envio = -1 ,
                Edicion = EdicionFestival ,
                CategoriaId = -1 ,
                PaisId = -1 ,
                NacionalidadId = -1,
            };
            // ----------------------------------
            var _model = GetModelShortFilmFilter(_filter, ListShortFilm);
            // ----------------------------------
            SetViewBagIndex(_filter);
            // ----------------------------------
            return View(_model);
            // ----------------------------------
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Index(AdminFilmsFilterConfViewModel _filterConf)
        {
            var _filter = new AdminFilmsFilterViewModel()
            {
                Activo = _filterConf.Filter.Activo,
                Preseleccion = _filterConf.Filter.Preseleccion,
                Sel_Oficial = _filterConf.Filter.Sel_Oficial,
                Ganador = _filterConf.Filter.Ganador,
                Etapa = _filterConf.Etapa,
                Envio = _filterConf.Envio,
                Edicion = _filterConf.Edicion,
                CategoriaId = _filterConf.CategoriaId,
                PaisId = _filterConf.PaisId,
                NacionalidadId = _filterConf.NacionalidadId,
            };
            // ----------------------------------
            //var _model = GetModelShortFilmFilter(_filter, GetListShortFilmFilter(_filter, ListShortFilm));
            var _model = GetModelShortFilmFilter(_filter, ListShortFilm);
            // ----------------------------------
            SetViewBagIndex(_filter);
            // ----------------------------------
            return View(_model);
            // ----------------------------------
        }
        #endregion

        /*------------------------------------------------*/
        /*------------------------------------------------*/
        /*------------------------------------------------*/
        #region Detail

        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Detail( int? id )
        {
            if (UserActive != null)
            {
                AppShortFilm _ShortFilm = new AppShortFilm();
                ActionResult _ActionResult = ValidAction(ref id, ref _ShortFilm, false, false);
                if (_ActionResult != null)
                {
                    return _ActionResult;
                }

                ViewBag.Etapa = _ShortFilm.Etapa;
                ViewBag.ShortFilmId = _ShortFilm.Id;
                ViewBag.IsCloseConvocatoria = IsCloseConvocatoria;

                ViewBag.Operations = new SelectList(ListOperations, "Id", "Operation", GetEstatusShortFilm(_ShortFilm));
                ViewBag.EtapaEdit = new SelectList(ListEtapaEdit, "Id", "Etapa", _ShortFilm.Etapa);
                return View(_ShortFilm);
            }

            return HttpNotFound();
        }


        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Detail(AdminFilmsOperationViewModel _filterConf)
        {
            if (UserActive != null)
            {
                AppShortFilm _ShortFilm = db.AppShortFilm.Find(_filterConf.Id);

                if (_ShortFilm != null && ModelState.IsValid)
                {
                    _ShortFilm.Preseleccion = false;
                    _ShortFilm.Sel_Oficial = false;
                    _ShortFilm.Ganador = false;
                    _ShortFilm.Activo = false;

                    switch (_filterConf.Operations)
                    {
                        case 0:  //Preselección
                            _ShortFilm.Activo = true;
                            break;
                        case 1:  //Preselección
                            _ShortFilm.Activo = true;
                            _ShortFilm.Preseleccion = true;
                            break;
                        case 2: // Selección Oficial
                            _ShortFilm.Activo = true;
                            _ShortFilm.Preseleccion = true;
                            _ShortFilm.Sel_Oficial = true;
                            break;

                        case 3: // Selección Oficial
                            _ShortFilm.Activo = true;
                            _ShortFilm.Preseleccion = false;
                            _ShortFilm.Sel_Oficial = true;
                            break;
                        //case 3: // Ganador
                        //    _ShortFilm.Activo = true;
                        //    _ShortFilm.Preseleccion = true;
                        //    _ShortFilm.Sel_Oficial = true;
                        //    _ShortFilm.Ganador = true;
                        //    break;
                        case 4: // Eliminar
                            _ShortFilm.Activo = false;
                            break;                   
                    }

                    _ShortFilm.Etapa = _filterConf.EtapaEdit;

                    db.SaveChanges();

                    if (_filterConf.ActiveNotification)
                    {
                        switch (_filterConf.Operations)
                        {
                            case 1:  //Preselección
                                SendMailPreseleccion(_ShortFilm);
                                break;
                            case 2: // Selección Oficial
                                SendMailSeleccionOficial(_ShortFilm);
                                break;
                        }
                    }
                }

                ViewBag.Etapa = _ShortFilm.Etapa;
                ViewBag.ShortFilmId = _ShortFilm.Id;
                ViewBag.IsCloseConvocatoria = IsCloseConvocatoria;

                ViewBag.Operations = new SelectList(ListOperations, "Id", "Operation", GetEstatusShortFilm(_ShortFilm));
                ViewBag.EtapaEdit = new SelectList(ListEtapaEdit, "Id", "Etapa", _ShortFilm.Etapa);
                return View(_ShortFilm);
            }

            return HttpNotFound();
        }
        #endregion

        /*------------------------------------------------*/
        /*------------------------------------------------*/
        /*------------------------------------------------*/
        #region CreateVideo
        [Authorize(Roles = "admin")]
        public ActionResult CreateVideo(int? id)
        {
            if (UserActive != null)
            {
                AppShortFilm _ShortFilm = new AppShortFilm();

                ActionResult _ActionResult = ValidAction(ref id, ref _ShortFilm, false, false);
                if (_ActionResult != null)
                {
                    return _ActionResult;
                }

                ViewBag.Etapa = _ShortFilm.Etapa;
                ViewBag.ShortFilmId = _ShortFilm.Id;
                return View(_ShortFilm);
            }
            return HttpNotFound();

        }
        #endregion

        /*------------------------------------------------*/
        /*------------------------------------------------*/
        /*------------------------------------------------*/
        #region Result
        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Result()
        {
            var _filter = new AdminFilmsFilterViewModel
            {
                Activo = true,
                Preseleccion = true,
                Sel_Oficial = false,
                Ganador = false,
                Etapa = EtapaRegistroFin,
                Envio = -1,
                Edicion = EdicionFestival,
                CategoriaId = -1,
                PaisId = -1,
                NacionalidadId = -1,
            };
            // ----------------------------------
            var _model = GetModelShortFilmJuradoFilter(_filter, ListShortFilmSeleccionOficial);
            // ----------------------------------
            SetViewBagIndex(_filter);
            // ----------------------------------
            return View(_model);
            // ----------------------------------
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Result(AdminFilmsFilterConfViewModel _filterConf)
        {
            var _filter = new AdminFilmsFilterViewModel
            {
                Activo = true,
                Preseleccion = true,
                Sel_Oficial = _filterConf.Filter.Sel_Oficial,
                Ganador = _filterConf.Filter.Ganador,
                Etapa = EtapaRegistroFin,
                Envio = -1,
                Edicion = EdicionFestival,
                CategoriaId = _filterConf.CategoriaId,
                PaisId = -1,
                NacionalidadId = _filterConf.NacionalidadId,

            };
            // ----------------------------------
            var _model = GetModelShortFilmJuradoFilter(_filter, ListShortFilmSeleccionOficial);
            // ----------------------------------
            SetViewBagIndex(_filter);
            // ----------------------------------

Controllers/ConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECO._2015.Controllers
{
    public class ConfigController : Controller
    {
        [Authorize(Roles = "admin")]
        public ActionResult Boletin()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Contacto()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Edicion()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Evento()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult EventoFestival()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Muestra()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Patrocinador()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Programa()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Proyeccion()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Sede()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Jurado()
        {
            return View();
        }
    }
}

Controllers/PublicController.cs
using ECO._2015.Bussiness;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECO._2015.Controllers
{
    public class PublicController : MsgBussines
    {
        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Report()
        {
            ViewBag.Service = "/api/PublicService/Report";
            ViewBag.Title = "Estadísticas  | Statistics ";
            return View();
        }

        public ActionResult Report2014()
        {
            ViewBag.Service = "/api/PublicService/Report2014";
            ViewBag.Title = "Estadísticas 2014 | Statistics 2014";
            return View("Report");
        }

        public ActionResult Report2015()
        {
            ViewBag.Service = "/api/PublicService/Report2015";
            ViewBag.Title = "Estadísticas 2015 | Statistics 2015";
            return View("Report");
        }
    }
}

Views/Shared/_Footer.cshtml
<div class="footer" style="display:none;">
    <div>
        <strong>Copyright</strong> Ecofilm Festival  &copy; @ViewBag.EdicionFestival
    </div>
</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("head", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ecofilm 2014", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated && User.IsInRole("participante"))
                    {
                        <li>@Html.ActionLink("Mis Cortos | My Short Films", "Index", "ShortFilms")</li>
                    }

                    @if (User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink("Prensa", "Index", "Prensa")</li>
                        <li>@Html.ActionLink("Jurado", "PreseleccionJurado", "AdminFilms")</li>
                        <li>@Html.ActionLink("Video Galería", "ViewSelOf", "AdminFilms")</li>
                        <li>@Html.ActionLink("Ganadores", "ViewGanador", "AdminFilms")</li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Inscritos <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Inscritos", "Index", "AdminFilms")</li>
                                <li>@Html.ActionLink("Inscritos | Envio Correo", "Correo", "AdminFilms")</li>
                                <li>@Html.ActionLink("Inscritos | Video", "Video", "AdminFilms")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Proceso", "Proceso", "AdminFilms")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Preselección <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Preseleción", "Preseleccion", "AdminFilms")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Preseleccion | Nacional", "PreseleccionNacional", "AdminFilms")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Preseleccion | Nacional | Documental", "PreseleccionNacionalDocumental", "AdminFilms")</li>
                                <li>@Html.ActionLink("Preseleccion | Nacional | Animación", "PreseleccionNacionalAnimacion", "AdminFilms")</li>
                                <li>@Html.ActionLink("Preseleccion | Nacional | Ficción", "PreseleccionNacionalFiccion", "AdminFilms")</li>
                                <li>@Html.ActionLink("Preseleccion | Nacional | Campaña Audiovisual", "PreseleccionNacionalCampana", "AdminFilms")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Preseleccion | Internacional", "PreseleccionInternacional", "AdminFilms")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Preseleccion | Internacional | Documental ", "PreseleccionInternacionalDocumental", "AdminFilms")</li>
                                <li>@Html.ActionLink("Preseleccion | Internacional | Animación", "PreseleccionInternacionalAnimacion", "AdminFilms")</li>
                                <li>@Html.ActionLink("Preseleccion | Internacional | Ficción ", "PreseleccionInternacionalFiccion", "AdminFilms")</li>
                                <li>@Html.ActionLink("Preseleccion | Internacional | Campaña AudioVisual", "PreseleccionInternacionalCampana", "AdminFilms")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Selección Oficial <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Sel. Oficial", "SelOficial", "AdminFilms")</li>
                                <li>@Html.ActionLink("Sel. Oficial | Nacional", "SelOficialNacional", "AdminFilms")</li>
                                <li>@Html.ActionLink("Sel. Oficial | Internacional ", "SelOficialInternacional", "AdminFilms")</li>
                            </ul>
                        </li>

                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <div>&nbsp;<hr /></div>
        <div class="row">
            <footer>
                <div class="text-center" style="border:0px solid #000;">
                    <img src="@Url.Content("~/Content/Images/barra.png")" class="img-responsive" style="display:inline-block;" />
                    <p style="margin:10px;"><strong>Cualquier problema o duda te ayudamos: admin@ecofilmfestival.org o al 56626227 y 5662 0553</strong> </p>
                    <p style="margin:10px;">&copy; @DateTime.Now.Year - Ecofilm Festival</p>
                </div>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/style-functions")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutClear.cshtml
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Ecofilm Festival</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet">

    <link href="~/Content/css/animate.css" rel="stylesheet">
    <link href="~/Content/css/style.css" rel="stylesheet">
    <link href="~/Scripts/FlipClock/flipclock.css" rel="stylesheet" />
    @RenderSection("style", required: false)
</head>

<body class="gray-bg">
    <div class="container text-center animated fadeInDown">

        <div class="row m-t-lg">

            <div class="col-lg-12">

            </div>

            <div class="col-lg-4">
                @RenderBody()

            </div>
            <div class="col-lg-8">
                @if (ViewBag.IsValidDate)
                {
                    <div class=" row">
                        <div class="col-lg-6">
                            <div class="widget white-bg p-lg text-center">
                                <div class="m-b-md">
                                    <h5>IMPORTANTE</h5>
                                    <p>
                                        ¿Fuiste participante de la edición anterior? Tus datos de acceso se encuentran
                                        registrados, en caso de no recordar tu contraseña puedes recuperarla con tu mail de
                                        acceso.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="widget white-bg p-lg text-center">
                                <div class="m-b-md">
                                    <h5>IMPORTANT</h5>
                                    <p>
                                        Were you a participant in the previous edition? You Access data is registered, if you don´t
                                        remember your password you can recover it by your mail Access.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                }


                @if (ViewBag.IsValidDate)
                {
                    <div class="widget white-bg p-lg text-center">
                        <div class="m-b-md">
                            <h3 class="font-bold no-margins" style="margin: 0 0 3em 0!important;">
                                Estas a tiempo para registrar tu corto! | Time left to register your film!
                            </h3>
                            <div class="clock" style="margin:2em 0;"></div>

                            <h3 class="font-bold no-margins">
                                <small>
                                    Cierre de Convocatoria | Call closing @ViewBag.DateCloseFullSting
                                </small>
                            </h3>
                            @RenderSection("rigthBottom", required: false)

                        </div>
                    </div>
                }
                else
                {

                    <div class="widget white-bg p-lg">
                        <div class="m-b-md">
                            @Html.Partial("~/Views/ShortFilms/RegisterClose/_CierreMsg.cshtml")
                            @RenderSection("rigthBottom", required: false)
                        </div>
                    </div>
                }



            </div>
        </div>




        <div class="row row-centered">
            <div class="col-md-12 col-centered">
                <div class="item">
                    <div class="content">
                        <p class="m-t">
                            <small>Cualquier problema o duda te ayudamos: admin@ecofilmfestival.org o al 56626227 y 5662 0553 </small>
                            <br />
                            <small> Any problems or questions we help: admin@ecofilmfestival.org or 56626227 and 5662 0553 </small>
                        </p>
                        <p class="m-t"> <small><strong>Copyright</strong> Ecofilm Festival  &copy; @ViewBag.EdicionFestival</small> </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Mainly scripts -->
    <script src="~/Scripts/plugins/jquery-2.1.1.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/FlipClock/flipclock.js"></script>
    <script type="text/javascript">
        var clock;
        $(document).ready(function () {

            callbacks = new Object();
            callbacks.stop = function () {
                $('.message').html('The clock has stopped!')
            }
            console.warn("Hora del Cierre Real", "@ViewBag.DateCloseFullSting")
            console.warn("Hora del Cierre Real", "@ViewBag.DateHourSting")
            var from = ("@ViewBag.DateCloseSting").split("/");
            var hour = ("@ViewBag.DateHourSting").split(":");
            var t1 = new Date(from[2], from[1] - 1, from[0] - 1, hour[0], hour[1], 0, 0);
            var t2 = new Date();
            var dif = t1.getTime() - t2.getTime();

            var Seconds_from_T1_to_T2 = dif / 1000;
            var Seconds_Between_Dates = Math.floor(Math.abs(Seconds_from_T1_to_T2));
            clock = $('.clock').FlipClock(Seconds_Between_Dates, {
                clockFace: 'DailyCounter',
                autoStart: false,
                language: 'es-es',
                callbacks: callbacks
            });
            clock.setCountdown(true);
            clock.start();

        });

    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="profile-element">
                    <img alt="image" class="" src="~/Content/images/logo-3-320x320-01-02.png" width="160" />
                </div>
                <div class="logo-element">
                    ECO
                </div>
            </li>
            @if (Request.IsAuthenticated && User.IsInRole("participante"))
            {
                <li class="active">
                    <a href="#"><i class="fa fa-film"></i> <span class="nav-label">Shortfilms</span> <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="@Url.Action("Index", "ShortFilms")">Mis Cortometrajes <span class="text-navy e15-sub-eng">My Short Films</span></a></li>
                    </ul>
                </li>
            }

            @if (Request.IsAuthenticated && User.IsInRole("admin"))
            {
                <li class="active">
                    <a href="#"><i class="fa fa-film"></i> <span class="nav-label">Administración</span> <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="@Url.Action("Index", "AdminFilms")">Listado Cortometrajes <span class="text-navy e15-sub-eng">My Short Films</span></a></li>
                        <li><a href="@Url.Action("Result", "AdminFilms")">Resultados <span class="text-navy e15-sub-eng">Results</span></a></li>
                    </ul>
                </li>
            }
            @if (Request.IsAuthenticated && User.IsInRole("admin"))
            {
                <li class="active">
                    <a href="#"><i class="fa fa-film"></i> <span class="nav-label">Estadisticas</span> <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="@Url.Action("Report", "Public")">Estadísticas <span class="text-navy e15-sub-eng">Statistics</span></a></li>
                        <li><a href="@Url.Action("Report2014", "Public")">2014 <span class="text-navy e15-sub-eng">2014</span></a></li>
                        <li><a href="@Url.Action("Report2015", "Public")">2015 <span class="text-navy e15-sub-eng">2015</span></a></li>
                    </ul>
                </li>
            }
            @if (Request.IsAuthenticated && User.IsInRole("jurado"))
            {
                <li class="active">
                    <a href="#"><i class="fa fa-film"></i> <span class="nav-label">Jurado</span> <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="@Url.Action("Index", "Jurado")">Listado Cortometrajes <span class="text-navy e15-sub-eng">My Short Films</span></a></li>
                    </ul>
                </li>
            }

            @if (Request.IsAuthenticated && User.IsInRole("view_films"))
            {
                <li class="active">
                    <a href="#"><i class="fa fa-film"></i> <span class="nav-label">Ver Cortos</span> <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="@Url.Action("ViewFilms", "AdminFilms")">Listado Cortometrajes <span class="text-navy e15-sub-eng">My Short Films</span></a></li>
                    </ul>
                </li>
            }
            @if (Request.IsAuthenticated && User.IsInRole("admin"))
            {
                <li class="active">
                    <a href="#"><i class="fa fa-wrench"></i> <span class="nav-label">Programa</span> <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="@Url.Action("Edicion", "Config")">Ediciones del Festival<span class="text-navy e15-sub-eng">List of Festival Editions</span></a></li>
                        <li><a href="@Url.Action("Sede", "Config")">Sedes<span class="text-navy e15-sub-eng">List of Locations</span></a></li>
                        <li><a href="@Url.Action("Programa", "Config")">Programa<span class="text-navy e15-sub-eng">List of Programs</span></a></li>
                        <li><a href="@Url.Action("Proyeccion", "Config")">Proyecciones<span class="text-navy e15-sub-eng">List of Proyection</span></a></li>
                        <li><a href="@Url.Action("Evento", "Config")">Eventos<span class="text-navy e15-sub-eng">List of Events</span></a></li>
                        <li><a href="@Url.Action("Muestra", "Config")">Muestras<span class="text-navy e15-sub-eng">List of Film Shows</span></a></li>
                    </ul>
                </li>
            }
            @if (Request.IsAuthenticated && User.IsInRole("admin"))
            {
                <li class="active">
                    <a href="#"><i class="fa fa-wrench"></i> <span class="nav-label">Configuración del Sistema</span> <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="@Url.Action("Patrocinador", "Config")">Listado de Patrocinadores<span class="text-navy e15-sub-eng">List of Sponsors</span></a></li>
                        <li><a href="@Url.Action("Boletin", "Config")">Listado de Boletines<span class="text-navy e15-sub-eng">List of Newsletters</span></a></li>
                        <li><a href="@Url.Action("EventoFestival", "Config")">Listado de Eventos del Festival<span class="text-navy e15-sub-eng">List Sponsors</span></a></li>
                    </ul>
                </li>
          
                <li class="active">
                    <a href="#"><i class="fa fa-wrench"></i> <span class="nav-label">Configuración de Jurado</span> <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="@Url.Action("Jurado", "Config")">Listado de Jurados<span class="text-navy e15-sub-eng">List of Sponsors</span></a></li>
                    </ul>
                </li>
            }
            @*<li class="landing_link">
                    <a target="_blank" href="Landing_page/index.html"><i class="fa fa-star-o"></i> <span class="nav-label">Landing Page</span> <span class="label label-warning pull-right">NEW</span></a>
                </li>*@
        </ul>
    </div>
</nav>