Models/App/Patrocinador.cs
namespace ECO._2015.Models.App
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SCH.Patrocinador")]
    public partial class Patrocinador
    {
        [Key]
        public int PK_IdPatrocinador { get; set; }

        public int FK_IdTipoPatrocinador__SCH { get; set; }

        [Required]
        [StringLength(50)]
        public string Descripcion_ES { get; set; }

        [Required]
        [StringLength(50)]
        public string Descripcion_EN { get; set; }

        public string Image { get; set; }

        public string WebSite { get; set; }

        public int? Edicion { get; set; }

        public int Orden { get; set; }

        public virtual Edicion Edicion1 { get; set; }

        public virtual TipoPatrocinador TipoPatrocinador { get; set; }

        public bool Home { get; set; }
    }
}

Models/Config/Patrocinador.cs
namespace ECO._2015.Models.Config
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SCH.Patrocinador")]
    public partial class Patrocinador
    {
        [Key]
        public int PK_IdPatrocinador { get; set; }

        public int FK_IdTipoPatrocinador__SCH { get; set; }

        [Required]
        [StringLength(50)]
        public string Descripcion_ES { get; set; }

        [Required]
        [StringLength(50)]
        public string Descripcion_EN { get; set; }

        public string Image { get; set; }

        public string WebSite { get; set; }

        public int? Edicion { get; set; }

        public virtual Edicion Edicion1 { get; set; }

        public virtual TipoPatrocinador TipoPatrocinador { get; set; }

        public bool Home { get; set; }
    }
}

Controllers/Config/PatrocinadorController.cs
using ECO._2015.Bussiness;
using ECO._2015.Controllers.Services;
using ECO._2015.Models.Config;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ECO._2015.Controllers.Config
{
    public class PatrocinadorController : UserBussines
    {
        /*
        private DBContextConfig _db = new DBContextConfig();

        // GET: Patrocinador
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Detail(int id)
        {
            var _entity = _db.Patrocinador.Find(id);
            if (_entity != null)
            {
                return View((PatrocinadorViewModel)_entity);
            }
            return RedirectToAction("Create");
        }

        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            var _entity = _db.Patrocinador.Find(id);
            if (_entity != null)
            {
                return View((PatrocinadorViewModel)_entity);
            }
            return RedirectToAction("Create");
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id, CreatePatrocinadorViewModel model)
        {
            model.PK_IdPatrocinador = id;
            if (ModelState.IsValid)
            {
                var _entity = (Patrocinador)model;
                var _original = (Patrocinador)_db.Patrocinador
                .Where(p => p.PK_IdPatrocinador == _entity.PK_IdPatrocinador).FirstOrDefault();
                // -----------------------------------
                try
                {
                    _db.Entry(_original).CurrentValues.SetValues(_entity);
                    _db.SaveChanges();
                    return Json(new
                    {
                        PatrocinadorId = _entity.PK_IdPatrocinador,
                        Url = string.Format("/Patrocinador/Detail/{0}", _entity.PK_IdPatrocinador)
                    });
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException ex)
                {
                    StringBuilder _builderInnerException = new StringBuilder();
                    foreach (var validationErrors in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            string _err = string.Format("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                            _builderInnerException.AppendFormat("{0} ", _err);
                            System.Diagnostics.Debug.WriteLine(_err);
                        }
                    }
                }
                catch (Exception e)
                {
                    System.Diagnostics.Debug.WriteLine(e.Message);
                    System.Diagnostics.Debug.WriteLine(e.Data);
                    return new BadRequest(e.InnerException.Message);
                }
            }
            return new BadRequest(ModelState);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Create(CreatePatrocinadorViewModel model)
        {
            if (ModelState.IsValid)
            {
                var _entity = (Patrocinador)model;
                _db.Patrocinador.Add(_entity);
                // -----------------------------------
                try
                {
                    _db.SaveChanges();
                    return Json(new
                    {
                        PatrocinadorId = _entity.PK_IdPatrocinador,
                        Url = string.Format("/Patrocinador/Detail/{0}", _entity.PK_IdPatrocinador)
                    });
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException ex)
                {
                    StringBuilder _builderInnerException = new StringBuilder();
                    foreach (var validationErrors in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            string _err = string.Format("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                            _builderInnerException.AppendFormat("{0} ", _err);
                            System.Diagnostics.Debug.WriteLine(_err);
                        }
                    }
                }
                catch (Exception e)
                {
                    System.Diagnostics.Debug.WriteLine(e.Message);
                    System.Diagnostics.Debug.WriteLine(e.Data);
                    return new BadRequest(e.InnerException.Message);
                }
            }
            foreach (PropertyDescriptor descriptor in TypeDescriptor.GetProperties(model))
            {
                string name = descriptor.Name;
                object value = descriptor.GetValue(model);
                System.Diagnostics.Debug.WriteLine("{0}={1}", name, value);
            }
            return new BadRequest("Cualquier Cosa");
        }
        */
    }
}

Views/Patrocinador/Create.cshtml
@{
    ViewBag.Title = "Nuevo Patrocinador | New Sponsor";
    Layout = "~/Views/Shared/_LayoutTemplateAng.cshtml";
}

@section breadcrumb
{
    <ol class="breadcrumb">
        <li class="active">
            @ViewBag.Title
        </li>
    </ol>
}

@section style
{
    <link href="~/Content/css/plugins/steps/jquery.steps.css" rel="stylesheet">
    <style>
        .wizard > .content > .body {
            position: relative !important;
            width: 100% !important;
        }
    </style>

    <style>
        .fileinput-button {
            position: relative;
            overflow: hidden;
        }

            .fileinput-button input {
                position: absolute;
                top: 0;
                right: 0;
                margin: 0;
                opacity: 0;
                -ms-filter: 'alpha(opacity=0)';
                font-size: 200px;
                direction: ltr;
                cursor: pointer;
            }

        @@media screen\9 {
            .fileinput-button input {
                filter: alpha(opacity=0);
                font-size: 100%;
                height: 100%;
            }
        }
    </style>
}

<div class="wrapper wrapper-content" ng-controller="PatrocinadorCrtl">
    <div class="row">
        <div class="col-sm-8">
            <div class="row">
                <form role="form" name="patrocinadorForm" class="form-horizontal">

                    <div class="form-group">
                        <label for="FK_IdTipoPatrocinador__SCH" class="col-md-2 control-label">Tipo de Patrocinador | Type Sponsor</label>
                        <div class="col-md-10">
                            <select class="form-control" ng-model="FK_IdTipoPatrocinador__SCH" required ng-options="item as item.Descripcion for item in tipoPatrocinadorList">
                                <option value="">Seleccione ... </option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Descripcion_ES" class="col-md-2 control-label">Descripcion en Español | Description in Spanish</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="Descripcion_ES" placeholder="Descripcion en Español | Description in Spanish" ng-model="patrocinador.Descripcion_ES" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Descripcion_EN" class="col-md-2 control-label">Descripcion en Inglés | Description in english</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="Descripcion_EN" placeholder="Descripcion en Inglés | Description in english" ng-model="patrocinador.Descripcion_EN" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Cartel_ES" class="col-md-2 control-label">Imagen | Image</label>
                        <div class="col-md-5">
                            <div class="ibox">
                                <div class="ibox-content">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-xs-12 file_upload">
                                            <span class="btn btn-success fileinput-button">
                                                <i class="glyphicon glyphicon-plus"></i>
                                                <span>Imagen | Image</span>
                                                <input class="fileupload"
                                                       type="file"
                                                       name="file"
                                                       accept="image/*"
                                                       data-id="Image" />
                                            </span>
                                            <br>
                                            <br>
                                            <div class="progress">
                                                <div class="progress-bar progress-bar-success"></div>
                                            </div>
                                            <div class="display" style="display:block">
                                                <img ng-src="{{patrocinador.Image}}" ng-show="patrocinador.Image != null" class="img-responsive img-thumbnail" />
                                            </div>
                                            <hr />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="WebSite" class="col-md-2 control-label">Sitio Web | WebSite</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="WebSite" placeholder="Imagen | Image" ng-model="patrocinador.WebSite" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Edicion" class="col-md-2 control-label">Edicion del Festival | Festival Edition</label>
                        <div class="col-md-10">
                            <select class="form-control" ng-model="FK_Edicion" required ng-options="item as item.Descripcion for item in edicionList">
                                <option value="">Seleccione ... </option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Home" class="col-md-2 control-label">Home | Home</label>
                        <div class="col-md-10">
                            <input type="checkbox" id="Home" placeholder="Home | Home" ng-model="patrocinador.Home" required>
                        </div>
                    </div>

                    <hr />
                    <div class="alert alert-danger" role="alert" ng-show="errorList.length > 0">
                        <strong>Oh snap!</strong>
                        <p ng-repeat="item in errorList">{{item}}</p>
                    </div>
                    <button type="button" class="btn btn-default" ng-click="crearPatrocinador()">Registro | Register</button>
                    <hr />
                </form>
            </div>
        </div>
    </div>
</div>


@section scripts
{
    <!---------------------------------------------->
    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/jQuery-File-Upload/js/vendor/jquery.ui.widget.js"></script>
    <script src="~/Scripts/jQuery-File-Upload/js/jquery.iframe-transport.js"></script>
    <script src="~/Scripts/jQuery-File-Upload/js/jquery.fileupload.js"></script>
    <!---------------------------------------------->
    <script>
        angular.module('App', [])
            .controller('PatrocinadorCrtl', ['$scope', '$http', '$window', function ($scope, $http, $window) {
                //---------------------------
                var ctrl = this;
                ctrl.Service = '/api/ConfigService/';
                ctrl.ServiceOp = '/Patrocinador/';
                //---------------------------
                ctrl.init = function () {
                    $http.get(ctrl.Service + 'SelectEdicion').then(function (response) { $scope.edicionList = response.data; });
                    $http.get(ctrl.Service + 'SelectTipoPatrocinador').then(function (response) { $scope.tipoPatrocinadorList = response.data})
                };
                //---------------------------
                $scope.errorList = [];
                $scope.patrocinador = {};
                //----------------------------------------
                $scope.$watch('FK_Edicion', function (v) {
                    if (v === undefined) return;
                    //----------------------------
                    console.log(v);
                    $scope.patrocinador.Edicion = v.Id;
                });

                $scope.$watch('FK_IdTipoPatrocinador__SCH', function (v) {
                    if (v === undefined) return;
                    //----------------------------
                    console.log(v);
                    $scope.patrocinador.FK_IdTipoPatrocinador__SCH = v.Id;
                });

                //----------------------------------------
                ctrl.init();
                $scope.crearPatrocinador = function () {
                    $scope.errorList = [];
                    $http.post(ctrl.ServiceOp + 'Create', $scope.patrocinador).then(
                        function (response) {
                            $window.location.href = response.data.Url;
                        }
                        , function (response) {
                            if (response.status == 400)
                            {
                                $scope.errorList = response.data;
                            }
                        }
                    );
                };

                $scope.setVariable = function (id, url) {
                    Object.defineProperty($scope.patrocinador, id, {
                        value: url,
                        writable: true,
                        enumerable: true,
                        configurable: true
                    });
                }
                angular.element('.file_upload').each(function () {
                    var progress_bar = $(this).find('.progress .progress-bar');
                    var id = $(this).find('.fileupload').attr("data-id");
                    var display = $(this).find('.display');
                    var img = $(this).find('.display img');

                    $(this).fileupload({
                        url: '/File/UploadFileImage',
                        acceptFileTypes: /(.|\/)(gif|jpe?g|png|pdf)$/i,
                        dataType: 'json',
                        add: function (e, data) {
                            data.submit();
                        },
                        done: function (e, data) {
                            console.log(data);
                            console.log($scope.patrocinador);
                            console.log(id);
                            //window.filesUpload[id] = data.result.pathfile;
                            console.log(data.result.pathfile);
                            $scope.$apply(function () {
                                $scope.setVariable(id, data.result.pathfile);
                            })
                        },
                        progressall: function (e, data) {
                            var progress = parseInt(data.loaded / data.total * 100, 10);
                            $(progress_bar).css(
                                'width',
                                progress + '%'
                            );
                        }
                    }).prop('disabled', !$.support.fileInput)
                    .parent().addClass($.support.fileInput ? undefined : 'disabled');
                });
            }])
        ;
    </script>
}

Views/Patrocinador/Detail.cshtml
@using ECO._2015.Controllers.Services
@model PatrocinadorViewModel

@{
    Layout = "~/Views/Shared/_LayoutTemplateAng.cshtml";
    ViewBag.Title = "Patrocinador | Patrocinador";
}

@section breadcrumb
{
    <ol class="breadcrumb">
        <li class="active">
            @ViewBag.Title
        </li>
    </ol>
}
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-sm-8">
            <div class="row">
                <form name="edicionFestivalForm" class="form-horizontal">
                    <div class="form-group">
                        <label for="Nombre_ES" class="col-md-2 control-label">Tipo de Patrocinador | Type of Sponsor</label>
                        <div class="col-md-10">
                            <p class="form-control-static">@Html.DisplayFor(model => model.tipoPatrocinador) </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Descripcion_ES" class="col-md-2 control-label">Descripcion en Español | Description in Spanish</label>
                        <div class="col-md-10">
                            <p class="form-control-static">@Html.DisplayFor(model => model.Descripcion_ES) </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Descripcion_EN" class="col-md-2 control-label">Descripcion en Inglés | Description in english</label>
                        <div class="col-md-10">
                            <p class="form-control-static">@Html.DisplayFor(model => model.Descripcion_EN) </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Tema_EN" class="col-md-2 control-label">Imagen | Image</label>
                        <div class="col-md-10">
                            <p class="form-control-static">
                                <a href="@Html.DisplayFor(model => model.Image)" target="_blank">
                                    <i class="fa fa-file-image-o" aria-hidden="true"></i>
                                </a>
                            </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Info_ES" class="col-md-2 control-label">Sitio Web | WebSite</label>
                        <div class="col-md-10">
                            <p class="form-control-static">
                                <a href="@Html.DisplayFor(model => model.WebSite)" target="_blank">
                                    <i class="fa fa-link" aria-hidden="true"></i>
                                </a>
                            </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Info_EN" class="col-md-2 control-label">Edicion del Festival| Festival Edition</label>
                        <div class="col-md-10">
                            <p class="form-control-static">@Html.DisplayFor(model => model.Edicion) - @Html.DisplayFor(model => model.descripcionEdicion) </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="BasesConvocatoria_ES" class="col-md-2 control-label">Home | Home</label>
                        <div class="col-md-10">
                            <p class="form-control-static">@Html.DisplayFor(model => model.Home) </p>
                        </div>
                    </div>

                    <hr />
                        <a href="@Url.Action("Edit", "Patrocinador")/@Html.DisplayFor(model => model.Id)" class="btn btn-success">
                            Editar
                        </a>
                        <a href="@Url.Action("Index", "Patrocinador")" class="btn btn-success">
                            Volver a la Lista
                        </a>
                    <hr />
                </form>
            </div>
        </div>
    </div>
</div>

Views/Patrocinador/Index.cshtml
@{
    ViewBag.Title = "Lista de los Patrocinadores | List Sponsors";
    Layout = "~/Views/Shared/_LayoutTemplateAng.cshtml";
}

@section breadcrumb
{
    <ol class="breadcrumb">
        <li class="active">
            @ViewBag.Title
        </li>
    </ol>
}

<div class="wrapper wrapper-content" ng-controller="PatrocinadorCtrl">
    <div class="row">
        <div class="col-sm-offset-10"><a href="@Url.Action("Create", "Patrocinador")" class="btn btn-warning">Crear</a></div>
        <div class="col-sm-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Tipo de Patrocinador</th>
                        <th>Descripcion</th>
                        <th>Imagen</th>
                        <th>Sitio Web</th>
                        <th>Edicion del Festival</th>
                        <th>Home</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="patrocinador in patrocinadorList">
                        <th scope="row">{{ patrocinador.Id }}</th>
                        <td>{{ patrocinador.tipoPatrocinador }}</td>
                        <td>{{ patrocinador.Descripcion_ES }}</td>
                        <td>
                            <div ng-show="patrocinador.Image != null">
                                <a href="{{ patrocinador.Image }}" target="_blank">
                                    <i class="fa fa-file-image-o" aria-hidden="true"></i>
                                </a>
                            </div>
                        </td>
                        <td>
                            <div ng-show="patrocinador.WebSite != null">
                                <a href="{{ patrocinador.WebSite }}" target="_blank">
                                    <i class="fa fa-link" aria-hidden="true"></i>
                                </a>
                            </div>
                        </td>
                        <td>{{ patrocinador.Edicion }} - {{patrocinador.descripcionEdicion}}</td>
                        <td>{{ patrocinador.Home }}</td>
                        <td>
                            <a href="@Url.Action("Detail", "Patrocinador")/{{patrocinador.Id}}" class="btn btn-primary">
                                Detalles</a>
                            <a href="@Url.Action("Edit", "Patrocinador")/{{patrocinador.Id}}" class="btn btn-success">
                                    Editar</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts
{
    <!---------------------------------------------->
    <script src="~/Scripts/angular.min.js"></script>
    <!---------------------------------------------->
    <script>
        angular.module('App', [])
            .controller('PatrocinadorCtrl', ['$scope', '$http', '$window', function ($scope, $http, $window) {
                //---------------------------
                var ctrl = this;
                ctrl.Service = '/api/ConfigService/';
                //---------------------------
                ctrl.init = function () {
                    $http.get(ctrl.Service + 'Patrocinador').then(function (response) { $scope.patrocinadorList = response.data; });
                };
                //---------------------------
                ctrl.init();
                //---------------------------
            }])
        ;
    </script>
}