Models/App/Sede.cs
namespace ECO._2015.Models.App
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SCH.Sede")]
    public partial class Sede
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sede()
        {
            Programa = new HashSet<Programa>();
        }

        [Key]
        public int PK_IdSede { get; set; }

        [Required]
        [StringLength(50)]
        public string Sede_ES { get; set; }

        [Required]
        [StringLength(50)]
        public string Sede_EN { get; set; }

        [Required]
        [StringLength(250)]
        public string Direccion { get; set; }

        public string url { get; set; }

        public string Image { get; set; }

        public string WebSite { get; set; }

        public int Edicion { get; set; }

        public virtual Edicion Edicion1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programa> Programa { get; set; }
    }
}

Models/Config/Sede.cs
namespace ECO._2015.Models.Config
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SCH.Sede")]
    public partial class Sede
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sede()
        {
            Programa = new HashSet<Programa>();
        }

        [Key]
        public int PK_IdSede { get; set; }

        [Required]
        [StringLength(50)]
        public string Sede_ES { get; set; }

        [Required]
        [StringLength(50)]
        public string Sede_EN { get; set; }

        [Required]
        [StringLength(250)]
        public string Direccion { get; set; }

        public string url { get; set; }

        public string Image { get; set; }

        public string WebSite { get; set; }

        public int Edicion { get; set; }

        public virtual Edicion Edicion1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programa> Programa { get; set; }
    }
}

Controllers/Config/SedeController.cs
using ECO._2015.Bussiness;
using ECO._2015.Controllers.Services;
using ECO._2015.Models.Config;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ECO._2015.Controllers.Config
{
    public class SedeController : UserBussines
    {
        /*
        private DBContextConfig _db = new DBContextConfig();

        // GET: Sede
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Detail(int id)
        {
            var _entity = _db.Sede.Find(id);
            if (_entity != null)
            {
                return View((DisplaySedeViewModel)_entity);
            }
            return RedirectToAction("Create");
        }

        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            var _entity = _db.Sede.Find(id);
            if (_entity != null)
            {
                return View((DisplaySedeViewModel)_entity);
            }
            return RedirectToAction("Create");
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id, CreateSedeViewModel model)
        {
            model.PK_IdSede = id;
            if (ModelState.IsValid)
            {
                var _entity = (Sede)model;
                var _original = (Sede)_db.Sede
                .Where(p => p.PK_IdSede == _entity.PK_IdSede).FirstOrDefault();
                // -----------------------------------
                try
                {
                    _db.Entry(_original).CurrentValues.SetValues(_entity);
                    _db.SaveChanges();
                    return Json(new
                    {
                        SedeId = _entity.PK_IdSede,
                        Url = string.Format("/Sede/Detail/{0}", _entity.PK_IdSede)
                    });
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException ex)
                {
                    StringBuilder _builderInnerException = new StringBuilder();
                    foreach (var validationErrors in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            string _err = string.Format("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                            _builderInnerException.AppendFormat("{0} ", _err);
                            System.Diagnostics.Debug.WriteLine(_err);
                        }
                    }
                }
                catch (Exception e)
                {
                    System.Diagnostics.Debug.WriteLine(e.Message);
                    System.Diagnostics.Debug.WriteLine(e.Data);
                    return new BadRequest(e.InnerException.Message);
                }
            }
            return new BadRequest(ModelState);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Create(CreateSedeViewModel model)
        {
            if (ModelState.IsValid)
            {
                var _entity = (Sede)model;
                _db.Sede.Add(_entity);
                // -----------------------------------
                try
                {
                    _db.SaveChanges();
                    return Json(new
                    {
                        SedeId = _entity.PK_IdSede,
                        Url = string.Format("/Sede/Detail/{0}", _entity.PK_IdSede)
                    });
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException ex)
                {
                    StringBuilder _builderInnerException = new StringBuilder();
                    foreach (var validationErrors in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            string _err = string.Format("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                            _builderInnerException.AppendFormat("{0} ", _err);
                            System.Diagnostics.Debug.WriteLine(_err);
                        }
                    }
                }
                catch (Exception e)
                {
                    System.Diagnostics.Debug.WriteLine(e.Message);
                    System.Diagnostics.Debug.WriteLine(e.Data);
                    return new BadRequest(e.InnerException.Message);
                }
            }
            foreach (PropertyDescriptor descriptor in TypeDescriptor.GetProperties(model))
            {
                string name = descriptor.Name;
                object value = descriptor.GetValue(model);
                System.Diagnostics.Debug.WriteLine("{0}={1}", name, value);
            }
            return new BadRequest("Cualquier Cosa");
        }
        */
    }
}

Views/Sede/Create.cshtml
@{
    ViewBag.Title = "Nueva Sede | New Location";
    Layout = "~/Views/Shared/_LayoutTemplateAng.cshtml";
}

@section breadcrumb
{
    <ol class="breadcrumb">
        <li class="active">
            @ViewBag.Title
        </li>
    </ol>
}

@section style
{
    <link href="~/Content/css/plugins/steps/jquery.steps.css" rel="stylesheet">
    <style>
        .wizard > .content > .body {
            position: relative !important;
            width: 100% !important;
        }
    </style>

    <style>
        .fileinput-button {
            position: relative;
            overflow: hidden;
        }

            .fileinput-button input {
                position: absolute;
                top: 0;
                right: 0;
                margin: 0;
                opacity: 0;
                -ms-filter: 'alpha(opacity=0)';
                font-size: 200px;
                direction: ltr;
                cursor: pointer;
            }

        @@media screen\9 {
            .fileinput-button input {
                filter: alpha(opacity=0);
                font-size: 100%;
                height: 100%;
            }
        }
    </style>
}

<div class="wrapper wrapper-content" ng-controller="SedeCrtl">
    <div class="row">
        <div class="col-sm-8">
            <div class="row">
                <form role="form" name="sedeForm" class="form-horizontal">

                    <div class="form-group">
                        <label for="Sede_ES" class="col-md-2 control-label">Sede en Español | Location in Spanish</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="Sede_ES" placeholder="Sede en Español | Location in Spanish" ng-model="sede.Sede_ES" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Sede_EN" class="col-md-2 control-label">Sede en Inglés | Location in english</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="Sede_EN" placeholder="Sede en Inglés | Location in english" ng-model="sede.Sede_EN" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Direccion" class="col-md-2 control-label">Dirección | Address</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="Direccion" placeholder="Dirección | Address" ng-model="sede.Direccion" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="url" class="col-md-2 control-label">Url | Url</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="url" placeholder="Imagen | Image" ng-model="sede.url" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Cartel_ES" class="col-md-2 control-label">Imagen | Image</label>
                        <div class="col-md-5">
                            <div class="ibox">
                                <div class="ibox-content">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-xs-12 file_upload">
                                            <span class="btn btn-success fileinput-button">
                                                <i class="glyphicon glyphicon-plus"></i>
                                                <span>Imagen | Image</span>
                                                <input class="fileupload"
                                                       type="file"
                                                       name="file"
                                                       accept="image/*"
                                                       data-id="Image" />
                                            </span>
                                            <br>
                                            <br>
                                            <div class="progress">
                                                <div class="progress-bar progress-bar-success"></div>
                                            </div>
                                            <div class="display" style="display:block">
                                                <img ng-src="{{sede.Image}}" ng-show="sede.Image != null" class="img-responsive img-thumbnail" />
                                            </div>
                                            <hr />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="WebSite" class="col-md-2 control-label">Sitio Web | WebSite</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="WebSite" placeholder="Imagen | Image" ng-model="sede.WebSite" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Edicion" class="col-md-2 control-label">Edicion del Festival | Festival Edition</label>
                        <div class="col-md-10">
                            <select class="form-control" ng-model="FK_Edicion" required ng-options="item as item.Descripcion for item in edicionList">
                                <option value="">Seleccione ... </option>
                            </select>
                        </div>
                    </div>

                    <hr />
                    <div class="alert alert-danger" role="alert" ng-show="errorList.length > 0">
                        <strong>Oh snap!</strong>
                        <p ng-repeat="item in errorList">{{item}}</p>
                    </div>
                    <button type="button" class="btn btn-default" ng-click="crearSede()">Guardar | Save</button>
                    <hr />
                </form>
            </div>
        </div>
    </div>
</div>


@section scripts
{
    <!---------------------------------------------->
    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/jQuery-File-Upload/js/vendor/jquery.ui.widget.js"></script>
    <script src="~/Scripts/jQuery-File-Upload/js/jquery.iframe-transport.js"></script>
    <script src="~/Scripts/jQuery-File-Upload/js/jquery.fileupload.js"></script>
    <!---------------------------------------------->
    <script>
        angular.module('App', [])
            .controller('SedeCrtl', ['$scope', '$http', '$window', function ($scope, $http, $window) {
                //---------------------------
                var ctrl = this;
                ctrl.Service = '/api/ConfigService/';
                ctrl.ServiceOp = '/Sede/';
                //---------------------------
                ctrl.init = function () {
                    $http.get(ctrl.Service + 'SelectEdicion').then(function (response) { $scope.edicionList = response.data; });
                };
                //---------------------------
                $scope.errorList = [];
                $scope.sede = {
                };
                //----------------------------------------
                $scope.$watch('FK_Edicion', function (v) {
                    if (v === undefined) return;
                    //----------------------------
                    console.log(v);
                    $scope.sede.Edicion = v.Id;
                });

                //----------------------------------------
                ctrl.init();
                $scope.crearSede = function () {
                    $scope.errorList = [];
                    $http.post(ctrl.ServiceOp + 'Create', $scope.sede).then(
                        function (response) {
                            $window.location.href = response.data.Url;
                        }
                        , function (response) {
                            if (response.status == 400)
                            {
                                $scope.errorList = response.data;
                            }
                        }
                    );
                };

                $scope.setVariable = function (id, url) {
                    Object.defineProperty($scope.sede, id, {
                        value: url,
                        writable: true,
                        enumerable: true,
                        configurable: true
                    });
                }
                angular.element('.file_upload').each(function () {
                    var progress_bar = $(this).find('.progress .progress-bar');
                    var id = $(this).find('.fileupload').attr("data-id");
                    var display = $(this).find('.display');
                    var img = $(this).find('.display img');

                    $(this).fileupload({
                        url: '/File/UploadFileImage',
                        acceptFileTypes: /(.|\/)(gif|jpe?g|png|pdf)$/i,
                        dataType: 'json',
                        add: function (e, data) {
                            data.submit();
                        },
                        done: function (e, data) {
                            console.log(data);
                            console.log($scope.sede);
                            console.log(id);
                            //window.filesUpload[id] = data.result.pathfile;

                            console.log(data.result.pathfile);
                            $scope.$apply(function () {
                                $scope.setVariable(id, data.result.pathfile);
                            })
                        },
                        progressall: function (e, data) {
                            var progress = parseInt(data.loaded / data.total * 100, 10);
                            $(progress_bar).css(
                                'width',
                                progress + '%'
                            );
                        }
                    }).prop('disabled', !$.support.fileInput)
                    .parent().addClass($.support.fileInput ? undefined : 'disabled');
                });
            }])
        ;
    </script>
}

Views/Sede/Detail.cshtml
@using ECO._2015.Controllers.Services
@model DisplaySedeViewModel

@{
    Layout = "~/Views/Shared/_LayoutTemplateAng.cshtml";
    ViewBag.Title = "Sede | Sede";
}

@section breadcrumb
{
    <ol class="breadcrumb">
        <li class="active">
            @ViewBag.Title
        </li>
    </ol>
}
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-sm-8">
            <div class="row">
                <form name="edicionFestivalForm" class="form-horizontal">

                    <div class="form-group">
                        <label for="Sede_ES" class="col-md-2 control-label">Sede en Español | Location in Spanish</label>
                        <div class="col-md-10">
                            <p class="form-control-static">@Html.DisplayFor(model => model.Sede_ES) </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Sede_EN" class="col-md-2 control-label">Sede en Inglés | Location in english</label>
                        <div class="col-md-10">
                            <p class="form-control-static">@Html.DisplayFor(model => model.Sede_EN) </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Direccion" class="col-md-2 control-label">Direccion | Address</label>
                        <div class="col-md-10">
                            <p class="form-control-static">@Html.DisplayFor(model => model.Direccion) </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="url" class="col-md-2 control-label">Url | Url</label>
                        <div class="col-md-10">
                            <p class="form-control-static">@Html.DisplayFor(model => model.url) </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Tema_EN" class="col-md-2 control-label">Imagen | Image</label>
                        <div class="col-md-10">
                            <p class="form-control-static">
                                <a href="@Html.DisplayFor(model => model.Image)" target="_blank">
                                    <i class="fa fa-file-image-o" aria-hidden="true"></i>
                                </a>
                            </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Info_ES" class="col-md-2 control-label">Sitio Web | WebSite</label>
                        <div class="col-md-10">
                            <p class="form-control-static">
                                <a href="@Html.DisplayFor(model => model.WebSite)" target="_blank">
                                    <i class="fa fa-link" aria-hidden="true"></i>
                                </a>
                            </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Info_EN" class="col-md-2 control-label">Edicion del Festival| Festival Edition</label>
                        <div class="col-md-10">
                            <p class="form-control-static">@Html.DisplayFor(model => model.Edicion) - @Html.DisplayFor(model => model.descripcionEdicion) </p>
                        </div>
                    </div>

                    <hr />
                        <a href="@Url.Action("Edit", "Sede")/@Html.DisplayFor(model => model.Id)" class="btn btn-success">
                            Editar
                        </a>
                        <a href="@Url.Action("Index", "Sede")" class="btn btn-success">
                            Volver a la Lista
                        </a>
                    <hr />
                </form>
            </div>
        </div>
    </div>
</div>

Views/Sede/Index.cshtml
@{
    ViewBag.Title = "Lista de Sedes | List of Locations";
    Layout = "~/Views/Shared/_LayoutTemplateAng.cshtml";
}

@section breadcrumb
{
    <ol class="breadcrumb">
        <li class="active">
            @ViewBag.Title
        </li>
    </ol>
}

<div class="wrapper wrapper-content" ng-controller="SedeCtrl">
    <div class="row">
        <div class="col-sm-offset-10"><a href="@Url.Action("Create", "Sede")" class="btn btn-warning">Crear</a></div>
        <div class="col-sm-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Sede</th>
                        <th>Direccion</th>
                        <th>Mapa</th>
                        <th>Imagen</th>
                        <th>Sitio Web</th>
                        <th>Edicion del Festival</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="sede in sedeList">
                        <th scope="row">{{ sede.Id }}</th>
                        <td>{{ sede.Sede_ES }}</td>
                        <td>{{ sede.Direccion }}</td>
                        <td>
                            <div ng-show="sede.url != null">
                                <a href="{{ sede.url }}" target="_blank">
                                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                                </a>
                            </div>
                        </td>
                        <td>
                            <div ng-show="sede.Image != null">
                                <a href="{{ sede.Image }}" target="_blank">
                                    <i class="fa fa-file-image-o" aria-hidden="true"></i>
                                </a>
                            </div>
                        </td>
                        <td>
                            <div ng-show="sede.WebSite != null">
                                <a href="{{ sede.WebSite }}" target="_blank">
                                    <i class="fa fa-link" aria-hidden="true"></i>
                                </a>
                            </div>
                        </td>
                        <td>{{ sede.Edicion }} - {{sede.descripcionEdicion}}</td>
                        <td>
                            <a href="@Url.Action("Detail", "Sede")/{{sede.Id}}" class="btn btn-primary">
                                Detalles</a>
                            <a href="@Url.Action("Edit", "Sede")/{{sede.Id}}" class="btn btn-success">
                                    Editar</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts
{
    <!---------------------------------------------->
    <script src="~/Scripts/angular.min.js"></script>
    <!---------------------------------------------->
    <script>
        angular.module('App', [])
            .controller('SedeCtrl', ['$scope', '$http', '$window', function ($scope, $http, $window) {
                //---------------------------
                var ctrl = this;
                ctrl.Service = '/api/ConfigService/';
                //---------------------------
                ctrl.init = function () {
                    $http.get(ctrl.Service + 'Sede').then(function (response) { $scope.sedeList = response.data; });
                };
                //---------------------------
                ctrl.init();
                //---------------------------
            }])
        ;
    </script>
}