Models/App/EventoFestival.cs
namespace ECO._2015.Models.App
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("PRE.EventoFestival")]
    public partial class EventoFestival
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventoFestival()
        {
            EventoNotas = new HashSet<EventoNotas>();
            EventosImagen = new HashSet<EventosImagen>();
        }

        [Key]
        public int PK_IdEventoFestival { get; set; }

        public int FK_IdEdicion__SCH { get; set; }

        [StringLength(50)]
        public string Nombre_ES { get; set; }

        [StringLength(50)]
        public string Nombre_EN { get; set; }

        [Column(TypeName = "date")]
        public DateTime? Fecha { get; set; }

        public virtual Edicion Edicion { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoNotas> EventoNotas { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventosImagen> EventosImagen { get; set; }
    }
}

Models/Config/EventoFestival.cs
namespace ECO._2015.Models.Config
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("PRE.EventoFestival")]
    public partial class EventoFestival
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventoFestival()
        {
            EventoNotas = new HashSet<EventoNotas>();
            EventosImagen = new HashSet<EventosImagen>();
        }

        [Key]
        public int PK_IdEventoFestival { get; set; }

        public int FK_IdEdicion__SCH { get; set; }

        [StringLength(50)]
        public string Nombre_ES { get; set; }

        [StringLength(50)]
        public string Nombre_EN { get; set; }

        [Column(TypeName = "date")]
        public DateTime? Fecha { get; set; }

        public virtual Edicion Edicion { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoNotas> EventoNotas { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventosImagen> EventosImagen { get; set; }
    }
}

Models/Prensa/EventoFestival.cs
namespace ECO._2015.Models.Prensa
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("PRE.EventoFestival")]
    public partial class EventoFestival
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventoFestival()
        {
            EventoNotas = new HashSet<EventoNotas>();
            EventosImagen = new HashSet<EventosImagen>();
        }

        [Key]
        public int PK_IdEventoFestival { get; set; }

        public int FK_IdEdicion__SCH { get; set; }

        [StringLength(50)]
        public string Nombre_ES { get; set; }

        [StringLength(50)]
        public string Nombre_EN { get; set; }

        [Column(TypeName = "date")]
        public DateTime? Fecha { get; set; }

        public virtual Edicion Edicion { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoNotas> EventoNotas { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventosImagen> EventosImagen { get; set; }
    }
}

Controllers/Config/EventoFestivalController.cs
using ECO._2015.Bussiness;
using ECO._2015.Controllers.Services;
using ECO._2015.Models.Config;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ECO._2015.Controllers.Config
{
    public class EventoFestivalController : UserBussines
    {
        /*private DBContextConfig _db = new DBContextConfig();

        // GET: EventoFestival
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Detail(int id)
        {
            var _entity = _db.EventoFestival.Find(id);
            if (_entity != null)
            {
                return View((DisplayEventoFestivalViewModel)_entity);
            }
            return RedirectToAction("Create");
        }

        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            var _entity = _db.EventoFestival.Find(id);
            if (_entity != null)
            {
                return View((DisplayEventoFestivalViewModel)_entity);
            }
            return RedirectToAction("Create");
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id, CreateEventoFestivalViewModel model)
        {
            model.PK_IdEventoFestival = id;
            if (ModelState.IsValid)
            {
                var _entity = (EventoFestival)model;
                var _original = (EventoFestival)_db.EventoFestival
                .Where(p => p.PK_IdEventoFestival == _entity.PK_IdEventoFestival).FirstOrDefault();
                // -----------------------------------
                try
                {
                    _db.Entry(_original).CurrentValues.SetValues(_entity);
                    _db.SaveChanges();
                    return Json(new
                    {
                        EventoFestivalId = _entity.PK_IdEventoFestival,
                        Url = string.Format("/EventoFestival/Detail/{0}", _entity.PK_IdEventoFestival)
                    });
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException ex)
                {
                    StringBuilder _builderInnerException = new StringBuilder();
                    foreach (var validationErrors in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            string _err = string.Format("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                            _builderInnerException.AppendFormat("{0} ", _err);
                            System.Diagnostics.Debug.WriteLine(_err);
                        }
                    }
                }
                catch (Exception e)
                {
                    System.Diagnostics.Debug.WriteLine(e.Message);
                    System.Diagnostics.Debug.WriteLine(e.Data);
                    return new BadRequest(e.InnerException.Message);
                }
            }
            return new BadRequest(ModelState);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Create(CreateEventoFestivalViewModel model)
        {
            foreach (PropertyDescriptor descriptor in TypeDescriptor.GetProperties(model))
            {
                string name = descriptor.Name;
                object value = descriptor.GetValue(model);
                System.Diagnostics.Debug.WriteLine("{0}={1}", name, value);
            }
            if (ModelState.IsValid)
            {
                var _entity = (EventoFestival)model;
                _db.EventoFestival.Add(_entity);
                // -----------------------------------
                try
                {
                    _db.SaveChanges();
                    return Json(new
                    {
                        EventoFestivalId = _entity.PK_IdEventoFestival,
                        Url = string.Format("/EventoFestival/Detail/{0}", _entity.PK_IdEventoFestival)
                    });
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException ex)
                {
                    StringBuilder _builderInnerException = new StringBuilder();
                    foreach (var validationErrors in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            string _err = string.Format("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                            _builderInnerException.AppendFormat("{0} ", _err);
                            System.Diagnostics.Debug.WriteLine(_err);
                        }
                    }
                }
                catch (Exception e)
                {
                    System.Diagnostics.Debug.WriteLine(e.Message);
                    System.Diagnostics.Debug.WriteLine(e.Data);
                    return new BadRequest(e.InnerException.Message);
                }
            }
            return new BadRequest("Cualquier Cosa");
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Note(DisplayEventoNotasViewModel model)
        {
            foreach (PropertyDescriptor descriptor in TypeDescriptor.GetProperties(model))
            {
                string name = descriptor.Name;
                object value = descriptor.GetValue(model);
                System.Diagnostics.Debug.WriteLine("{0}={1}", name, value);
            }
            if (ModelState.IsValid)
            {
                //var _entity = (EventoNotas)model;
                //_db.EventoNotas.Add(_entity);
                // -----------------------------------
                try
                {
                    //_db.SaveChanges();
                    //return Json(new
                    //{
                    //    EventoFestivalId = _entity.PK_IdEventoNotas,
                    //    Nota = _entity.Nota
                    //});
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException ex)
                {
                    StringBuilder _builderInnerException = new StringBuilder();
                    foreach (var validationErrors in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            string _err = string.Format("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                            _builderInnerException.AppendFormat("{0} ", _err);
                            System.Diagnostics.Debug.WriteLine(_err);
                        }
                    }
                }
                catch (Exception e)
                {
                    System.Diagnostics.Debug.WriteLine(e.Message);
                    System.Diagnostics.Debug.WriteLine(e.Data);
                    System.Diagnostics.Debug.WriteLine(e.InnerException);
                    return new BadRequest(e.InnerException.Message);
                }
            }
            return new BadRequest(ModelState);
        }
        */
    }
}

Views/EventoFestival/Create.cshtml
@{
    ViewBag.Title = "Nuevo EventoFestival | New Newsletter";
    Layout = "~/Views/Shared/_LayoutTemplateAng.cshtml";
}

@section breadcrumb
{
    <ol class="breadcrumb">
        <li class="active">
            @ViewBag.Title
        </li>
    </ol>
}

<div class="wrapper wrapper-content" ng-controller="EventoFestivalCrtl">
    <div class="row">
        <div class="col-sm-8">
            <div class="row">
                <form role="form" name="EventoFestivalForm" class="form-horizontal">

                    <div class="form-group">
                        <label for="FK_IdEdicion__SCH" class="col-md-2 control-label">Edicion del Festival | Festival Edition</label>
                        <div class="col-md-10">
                            <select class="form-control" ng-model="FK_IdEdicion__SCH" required ng-options="item as item.Descripcion for item in edicionList">
                                <option value="">Seleccione ... </option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Nombre_ES" class="col-md-2 control-label">Nombre en Español | Name in Spanish</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="Nombre_ES" placeholder="Nombre en Español | Name in Spanish" ng-model="eventoFestival.Nombre_ES" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Nombre_EN" class="col-md-2 control-label">Nombre en Inglés | Name in english</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="Nombre_EN" placeholder="Nombre en Inglés | Name in english" ng-model="eventoFestival.Nombre_EN" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Fecha" class="col-md-2 control-label">Fecha Publicacion | Publish Date</label>
                        <div class="col-md-10">
                            <input type="date" id="Fecha" placeholder="Fecha Publicacion | Publish Date" ng-model="eventoFestival.FechaString" required>
                        </div>
                    </div>

                    <hr />
                    <div class="alert alert-danger" role="alert" ng-show="errorList.length > 0">
                        <strong>Oh snap!</strong>
                        <p ng-repeat="item in errorList">{{item}}</p>
                    </div>
                    <button type="button" class="btn btn-default" ng-click="crearEventoFestival()">Registro | Register</button>
                    <hr />
                </form>
            </div>
        </div>
    </div>
</div>


@section scripts
{
    <!---------------------------------------------->
    <script src="~/Scripts/angular.min.js"></script>
    <!---------------------------------------------->
    <script>
        angular.module('App', [])
            .controller('EventoFestivalCrtl', ['$scope', '$http', '$window', function ($scope, $http, $window) {
                //---------------------------
                var ctrl = this;
                ctrl.Service = '/api/ConfigService/';
                ctrl.ServiceOp = '/EventoFestival/';
                //---------------------------
                ctrl.init = function () {
                    $http.get(ctrl.Service + 'SelectEdicion').then(function (response) { $scope.edicionList = response.data; });
                };
                //---------------------------
                $scope.errorList = [];
                $scope.eventoFestival = {
                };
                //----------------------------------------
                $scope.$watch('FK_IdEdicion__SCH', function (v) {
                    if (v === undefined) return;
                    //----------------------------
                    $scope.eventoFestival.FK_IdEdicion__SCH = v.Id;
                });
                //----------------------------------------
                ctrl.init();
                $scope.crearEventoFestival = function () {
                    $scope.errorList = [];
                    $http.post(ctrl.ServiceOp + 'Create', $scope.eventoFestival).then(
                        function (response) {
                            $window.location.href = response.data.Url;
                        }
                        , function (response) {
                            if (response.status == 400)
                            {
                                $scope.errorList = response.data;
                            }
                        }
                    );
                };
            }]);
    </script>
}

Views/EventoFestival/Detail.cshtml
@using ECO._2015.Controllers.Services
@model DisplayEventoFestivalViewModel

@{
    Layout = "~/Views/Shared/_LayoutTemplateAng.cshtml";
    ViewBag.Title = "Patrocinador | Patrocinador";
}

@section breadcrumb
{
    <ol class="breadcrumb">
        <li class="active">
            @ViewBag.Title
        </li>
    </ol>
}
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-sm-8">
            <div class="row">
                <form name="edicionFestivalForm" class="form-horizontal">
                    <div class="form-group">
                        <label for="Edicion" class="col-md-2 control-label">Edicion del Festival | Festival Edition</label>
                        <div class="col-md-10">
                            <p class="form-control-static">@Html.DisplayFor(model => model.FK_IdEdicion__SCH) - @Html.DisplayFor(model => model.descripcionEdicion) </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Nombre_ES" class="col-md-2 control-label">Nombre en Español | Name in Spanish</label>
                        <div class="col-md-10">
                            <p class="form-control-static">@Html.DisplayFor(model => model.Nombre_ES) </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Nombre_EN" class="col-md-2 control-label">Nombre en Español | Name in Spanish</label>
                        <div class="col-md-10">
                            <p class="form-control-static">@Html.DisplayFor(model => model.Nombre_EN) </p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Fecha" class="col-md-2 control-label">Fecha Publicacion | Publish Date</label>
                        <div class="col-md-10">
                            <p class="form-control-static">@Html.DisplayFor(model => model.Fecha) </p>
                        </div>
                    </div>

                    <hr />
                    <a href="@Url.Action("Edit", "EventoFestival")/@Html.DisplayFor(model => model.Id)" class="btn btn-success">
                        Editar
                    </a>
                    <a href="@Url.Action("Index", "EventoFestival")" class="btn btn-success">
                        Volver a la Lista
                    </a>
                    <hr />
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h1>Notas</h1>
        </div>
        <div class="col-sm-6" ng-controller="EventoFestivalNotaCtrl">
            <div class="col-sm-6">
                <form role="form" name="EventoFestivalForm" class="form-horizontal">
                    <div class="form-group">
                        <label for="Nota" class="col-md-2 control-label">Nota | Note</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="Nota" placeholder="Nota | Note" ng-model="eventoFestivalNota.Nota" required>
                        </div>
                    </div>
                </form>
                <hr />
                    <button type="button" class="btn btn-info" ng-click="crearEventoFestivalNota()">Agregar Nota | Add Note</button>
                <hr />
            </div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nota</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="eventoFestival in eventoFestivalList">
                        <td>{{ eventoFestival.Nota }}</td>
                        <td>
                            <button type="button" class="btn btn-success" ng-click="editarEventoFestivalNota()">Editar</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts
{
    <!---------------------------------------------->
    <script src="~/Scripts/angular.min.js"></script>
    <!---------------------------------------------->
    <script>
        angular.module('App', [])
            .controller('EventoFestivalNotaCtrl', ['$scope', '$http', '$window', function ($scope, $http, $window) {
                //---------------------------
                var ctrl = this;
                ctrl.Service = '/api/ConfigService/';
                ctrl.ServiceOp = '/EventoFestival/';
                var idEventoFestivalNota = "@Model.Id";
                console.log(idEventoFestivalNota);
                $scope.eventoFestivalList = [];
                $scope.eventoFestivalNota = {};
                //---------------------------
                ctrl.init = function () {
                    $scope.eventoFestivalNota.FK_IdEventoFestival__SCH = idEventoFestivalNota;
                    $http.get(ctrl.Service + 'EventoNotas/'+ idEventoFestivalNota).then(function (response) {
                        $scope.eventoFestivalList = response.data;
                        console.log($scope.eventoFestivalList);
                    });
                };
                //---------------------------
                ctrl.init();
                //---------------------------
                $scope.crearEventoFestivalNota = function () {
                    $scope.errorList = [];
                    $http.post(ctrl.ServiceOp + 'Note', $scope.eventoFestivalNota).then(
                        function (response) {
                            $scope.eventoFestivalList.push({ 'Nota': response.data.Nota })
                        }
                        , function (response) {
                            if (response.status == 400) {
                                $scope.errorList = response.data;
                            }
                        }
                    );
                }
            }])
            
        ;
    </script>
}

Views/EventoFestival/Edit.cshtml
@using ECO._2015.Controllers.Services
@model DisplayEventoFestivalViewModel

@{
    ViewBag.Title = "Editar EventoFestival | Edit NewsLetter";
    Layout = "~/Views/Shared/_LayoutTemplateAng.cshtml";
}

@section breadcrumb
{
    <ol class="breadcrumb">
        <li class="active">
            @ViewBag.Title
        </li>
    </ol>
}

<div class="wrapper wrapper-content" ng-controller="EventoFestivalCrtl">
    <div class="row">
        <div class="col-sm-8">
            <div class="row">
                <form role="form" name="EventoFestivalForm" class="form-horizontal">

                    <div class="form-group">
                        <label for="FK_IdEdicion__SCH" class="col-md-2 control-label">Edicion del Festival | Festival Edition</label>
                        <div class="col-md-10">
                            <select class="form-control" ng-model="FK_IdEdicion__SCH" required ng-options="item as item.Descripcion for item in edicionList">
                                <option value="">Seleccione ... </option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Nombre_ES" class="col-md-2 control-label">Nombre en Español | Name in Spanish</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="Nombre_ES" placeholder="Nombre en Español | Name in Spanish" ng-model="eventoFestival.Nombre_ES" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Nombre_EN" class="col-md-2 control-label">Nombre en Inglés | Name in english</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" id="Nombre_EN" placeholder="Nombre en Inglés | Name in english" ng-model="eventoFestival.Nombre_EN" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Fecha" class="col-md-2 control-label">Fecha Publicacion | Publish Date</label>
                        <div class="col-md-10">
                            <input type="date" id="Fecha" placeholder="Fecha Publicacion | Publish Date" ng-model="eventoFestival.FechaString" required>
                        </div>
                    </div>

                    <hr />
                    <div class="alert alert-danger" role="alert" ng-show="errorList.length > 0">
                        <strong>Oh snap!</strong>
                        <p ng-repeat="item in errorList">{{item}}</p>
                    </div>
                    <button type="button" class="btn btn-default" ng-click="editarEventoFestival()">Editar | Edit</button>
                    <hr />
                </form>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <!---------------------------------------------->
    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/moment/moment-with-locales.min.js"></script>
    <!---------------------------------------------->
    <script>
        angular.module('App', [])
            .controller('EventoFestivalCrtl', ['$scope', '$http', '$window', function ($scope, $http, $window) {
                //---------------------------
                var ctrl = this;
                ctrl.Service = '/api/ConfigService/';
                ctrl.ServiceOp = '/EventoFestival/';
                //---------------------------
                $scope.errorList = [];
                var idEventoFestival = "";
                $scope.eventoFestival = {};
                //----------------------------
                ctrl.init = function () {
                    $http.get(ctrl.Service + 'SelectEdicion').then(function (response) {
                        $scope.edicionList = response.data;
                        $scope.eventoFestival.FK_IdEdicion__SCH = "@Html.DisplayFor(model => model.FK_IdEdicion__SCH)";
                        $.each($scope.edicionList, function (key, value) {
                            if (value.Id == $scope.eventoFestival.FK_IdEdicion__SCH) {
                                $scope.FK_IdEdicion__SCH = $scope.edicionList[key];
                            }
                        });
                    });

                    $scope.eventoFestival.Nombre_ES = "@Html.DisplayFor(model => model.Nombre_ES)";
                    $scope.eventoFestival.Nombre_EN = "@Html.DisplayFor(model => model.Nombre_EN)";
                    $scope.eventoFestival.FechaString = new Date(moment(("@Html.DisplayFor(model => model.Fecha, "{0:dd/MM/yyyy}")".split(" 12:00:00 a. m."))[0], 'DD/MM/YYYY').format('YYYY-MM-DD'));
                    idEventoFestival = "@Html.DisplayFor(model => model.Id)";
                };
                //----------------------------------------
                $scope.$watch('FK_Edicion', function (v) {
                    if (v === undefined) return;
                    //----------------------------
                    $scope.eventoFestival.Edicion = v.Id;
                });

                //----------------------------------------
                ctrl.init();
                //----------------------------
                $scope.editarEventoFestival = function () {
                    $scope.errorList = [];

                    $http.post(ctrl.ServiceOp + 'Edit', { 'id': idEventoFestival, 'model': $scope.eventoFestival }).then(
                        function (response) {
                            $window.location.href = response.data.Url;
                        }
                        , function (response) {
                            if (response.status == 400)
                            {
                                $scope.errorList = response.data;
                            }
                        }
                    );
                };
            }])
        ;
    </script>
}

Views/EventoFestival/Index.cshtml
@{
    ViewBag.Title = "Lista de Eventos del Festival | List of Festival Events";
    Layout = "~/Views/Shared/_LayoutTemplateAng.cshtml";
}

@section breadcrumb
{
    <ol class="breadcrumb">
        <li class="active">
            @ViewBag.Title
        </li>
    </ol>
}

<div class="wrapper wrapper-content" ng-controller="EventoFestivalCtrl">
    <div class="row">
        <div class="col-sm-offset-10"><a href="@Url.Action("Create", "EventoFestival")" class="btn btn-warning">Crear</a></div>
        <div class="col-sm-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Edicion del Festival</th>
                        <th>Nombre</th>
                        <th>Fecha</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="eventoFestival in eventoFestivalList">
                        <th scope="row">{{ eventoFestival.Id }}</th>
                        <td>{{ eventoFestival.FK_IdEdicion__SCH }} - {{eventoFestival.descripcionEdicion}}</td>
                        <td>{{ eventoFestival.Nombre_ES }}</td>
                        <td>{{ eventoFestival.Fecha }}</td>
                        <td>
                            <a href="@Url.Action("Detail", "EventoFestival")/{{eventoFestival.Id}}" class="btn btn-primary">
                                Detalles</a>
                            <a href="@Url.Action("Edit", "EventoFestival")/{{eventoFestival.Id}}" class="btn btn-success">
                                    Editar</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts
{
    <!---------------------------------------------->
    <script src="~/Scripts/angular.min.js"></script>
    <!---------------------------------------------->
    <script>
        angular.module('App', [])
            .controller('EventoFestivalCtrl', ['$scope', '$http', '$window', function ($scope, $http, $window) {
                //---------------------------
                var ctrl = this;
                ctrl.Service = '/api/ConfigService/';
                //---------------------------
                ctrl.init = function () {
                    $http.get(ctrl.Service + 'EventoFestival').then(function (response) { $scope.eventoFestivalList = response.data; });
                };
                //---------------------------
                ctrl.init();
                //---------------------------
            }])
        ;
    </script>
}